// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class BoardPageTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void boardPage() {
    driver.get("http://localhost:4000/sign_in");
    driver.manage().window().setSize(new Dimension(795, 697));
    driver.findElement(By.cssSelector("button")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("h3 > span")));
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#boards_nav span"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".logo"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector("span:nth-child(3)")).click();
    assertThat(driver.findElement(By.cssSelector("span:nth-child(3)")).getText(), is("John Doe"));
    {
      List<WebElement> elements = driver.findElements(By.id("crawler-sign-out"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.cssSelector("h3 > span")).getText(), is("My boards"));
    {
      List<WebElement> elements = driver.findElements(By.id("add_new_board"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector("#crawler-sign-out > span")).click();
  }
}
