// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.*;

public class Test3 {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void kire() throws InterruptedException {
        driver.get("http://localhost:4000/sign_in");
        driver.manage().window().setSize(new Dimension(758, 1013));
        driver.findElement(By.cssSelector("button")).click();

        Thread.sleep(3000);
        driver.findElement(By.cssSelector("h3 > span")).click();
        assertThat(driver.findElement(By.cssSelector("h3>span")).getText(), is("My boards"));
        {
            WebElement element = driver.findElement(By.cssSelector("h3 > span"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        {
            List<WebElement> elements = driver.findElements(By.id("add_new_board"));
            assert(elements.size() > 0);
        }
        driver.findElement(By.id("add_new_board")).click();
        {
            List<WebElement> elements = driver.findElements(By.id("add_new_board"));
            assert(elements.size() == 0);
        }
        driver.findElement(By.cssSelector("button")).click();
        assertThat(driver.getTitle(), is("Boards | Phoenix Trello"));
        driver.findElement(By.id("board_name")).sendKeys("gelo");
        {
            WebElement element = driver.findElement(By.id("board_name"));
            Boolean isEditable = element.isEnabled() && element.getAttribute("readonly") == null;
            assertTrue(isEditable);
        }
        {
            String value = driver.findElement(By.id("board_name")).getAttribute("value");
            assertThat(value, is("gelo"));
        }
        driver.findElement(By.id("board_name")).sendKeys("nice and attractive\\n");
        driver.findElement(By.linkText("cancel")).click();
        driver.findElement(By.id("add_new_board")).click();
        driver.findElement(By.id("board_name")).sendKeys("khelte thako");

        driver.findElement(By.cssSelector("#crawler-sign-out > span")).click();
        assertThat(driver.getTitle(), is("Sign in | Phoenix Trello"));
    }

    @Test
    public void singin() {
        driver.get("http://localhost:4000/sign_in");
        driver.manage().window().setSize(new Dimension(820, 696));
        driver.findElement(By.cssSelector("button")).click();
    }
    @Test
    public void createboard() {
        driver.get("http://localhost:4000/sign_in");
        driver.manage().window().setSize(new Dimension(820, 697));
        driver.findElement(By.cssSelector("button")).click();
        WebDriverWait wait = new WebDriverWait(driver, java.time.Duration.ofSeconds(10));
        wait.until(ExpectedConditions.elementToBeClickable(By.id("add_new_board")));
        driver.findElement(By.id("add_new_board")).click();
        driver.findElement(By.id("board_name")).sendKeys("abc board");
        driver.findElement(By.cssSelector("button")).click();
    }
    @Test
    public void viewBoards() {
        driver.get("http://localhost:4000/sign_in");
        driver.manage().window().setSize(new Dimension(820, 697));
        driver.findElement(By.cssSelector("button")).click();
        WebDriverWait wait = new WebDriverWait(driver, java.time.Duration.ofSeconds(10));
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("#boards_nav span")));
        driver.findElement(By.cssSelector("#boards_nav span")).click();
        wait.until(ExpectedConditions.elementToBeClickable(By.linkText("View all boards")));
        driver.findElement(By.linkText("View all boards")).click();
    }
    @Test
    public void signout() {
        driver.get("http://localhost:4000/sign_in");
        driver.manage().window().setSize(new Dimension(820, 697));
        driver.findElement(By.cssSelector("button")).click();
        WebDriverWait wait = new WebDriverWait(driver, java.time.Duration.ofSeconds(10));
        wait.until(ExpectedConditions.presenceOfElementLocated(By.id("crawler-sign-out")));
        WebElement signOut = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("#crawler-sign-out > span")));
        signOut.click();
    }
}
